#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 0
#include "MW_nvidia_init.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE NVIDIA Jetson
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS nvidiacoder.getDeviceAddressJetson
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_TCPIP_RUNINBACKGROUND 0
#define MW_CONNECTIONINFO_XCPONTCPIP_IPADDRESS nvidiacoder.getDeviceAddressJetson
#define MW_CONNECTIONINFO_XCPONTCPIP_PORT 17725
#define MW_CONNECTIONINFO_XCPONTCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_XCPONTCPIP_RUNINBACKGROUND 0
#define MW_EXTMODE_CONFIGURATION TCP/IP
#define MW_EXTMODE_SIGNALBUFFERSIZE 1000000.000000
#define MW_RTOS Linux
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_DETECTTASKOVERRUNS 0.000000
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_BOARDPARAMETERS_DEVICEADDRESS 192.168.1.110
#define MW_BOARDPARAMETERS_USERNAME spot-red
#define MW_BOARDPARAMETERS_PASSWORD srcl2023
#define MW_BOARDPARAMETERS_BUILDDIR /home/spot-red/ExperimentSoftware/
#define MW_BOARDPARAMETERS_DISPLAYENV 0.0
#define MW_RUNTIME_BUILDACTION 1
#define MW_CAN_CANBUSSPEED 10
#define MW_CAN_CANOSCILLATORFREQUENCY 1
#define MW_CAN_INTERRUPTPIN 12
#define MW_CAN_ALLOWALLFILTER 1
#define MW_CAN_BUFFER0IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK0 0
#define MW_CAN_ACCEPTANCEFILTER0 255
#define MW_CAN_INVERSEFILTER0 0
#define MW_CAN_BUFFER1IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK1 0
#define MW_CAN_ACCEPTANCEFILTER1 255
#define MW_CAN_INVERSEFILTER1 0
#define MW_CAN_BUFFER2IDTYPE 1
#define MW_CAN_ACCEPTANCEMASK2 0
#define MW_CAN_ACCEPTANCEFILTER2 255
#define MW_CAN_INVERSEFILTER2 0
#define MW_CAN_BUFFER3IDTYPE 1
#define MW_CAN_ACCEPTANCEMASK3 0
#define MW_CAN_ACCEPTANCEFILTER3 255
#define MW_CAN_INVERSEFILTER3 0
#define MW_MODBUS_MODBUS_COMMS 0
#define MW_MODBUS_MODBUS_MODE 0
#define MW_MODBUS_MODBUS_SERVERREMOTEPORT 502
#define MW_MODBUS_MODBUS_SERVERLOCALPORT 502
#define MW_MODBUS_MODBUS_CONFIGCOIL 49
#define MW_MODBUS_MODBUS_COILADDR 0
#define MW_MODBUS_MODBUS_COILNUM 1
#define MW_MODBUS_MODBUS_CONFIGINPUT 49
#define MW_MODBUS_MODBUS_INPUTADDR 0
#define MW_MODBUS_MODBUS_INPUTNUM 1
#define MW_MODBUS_MODBUS_CONFIGHOLDINGREG 49
#define MW_MODBUS_MODBUS_HOLDINGREGADDR 0
#define MW_MODBUS_MODBUS_HOLDINGREGNUM 1
#define MW_MODBUS_MODBUS_CONFIGINPUTREG 49
#define MW_MODBUS_MODBUS_INPUTREGADDR 0
#define MW_MODBUS_MODBUS_INPUTREGNUM 1
#define MW_MODBUS_MODBUS_MASTERTIMEOUT 100
#define MW_SENSOR_FILELOCATION codertarget.jetson.sensors
#define MW_MQTT_BROKERADDRESS mqtt3.thingspeak.com
#define MW_MQTT_USERNAME 
#define MW_MQTT_PASSWORD 
#define MW_MQTT_CLIENTID 
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
